package code.demo.model;

// Generated Mar 11, 2014 9:18:20 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Platform generated by hbm2java
 */
public class Platform implements java.io.Serializable {

	private Short id;
	private String platformName;
	private Set<TestRecord> testRecords = new HashSet<TestRecord>(0);

	public Platform() {
	}

	public Platform(String platformName, Set<TestRecord> testRecords) {
		this.platformName = platformName;
		this.testRecords = testRecords;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getPlatformName() {
		return this.platformName;
	}

	public void setPlatformName(String platformName) {
		this.platformName = platformName;
	}

	public Set<TestRecord> getTestRecords() {
		return this.testRecords;
	}

	public void setTestRecords(Set<TestRecord> testRecords) {
		this.testRecords = testRecords;
	}

}
