package code.demo.model;

// Generated Mar 11, 2014 9:18:20 PM by Hibernate Tools 4.0.0

/**
 * TestRecord generated by hbm2java
 */
public class TestRecord implements java.io.Serializable {

	private Integer id;
	private Result result;
	private TestPhase testPhase;
	private Platform platform;

	public TestRecord() {
	}

	public TestRecord(Result result, TestPhase testPhase, Platform platform) {
		this.result = result;
		this.testPhase = testPhase;
		this.platform = platform;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Result getResult() {
		return this.result;
	}

	public void setResult(Result result) {
		this.result = result;
	}

	public TestPhase getTestPhase() {
		return this.testPhase;
	}

	public void setTestPhase(TestPhase testPhase) {
		this.testPhase = testPhase;
	}

	public Platform getPlatform() {
		return this.platform;
	}

	public void setPlatform(Platform platform) {
		this.platform = platform;
	}

}
